FROM python:3.9.12

WORKDIR /

RUN apt clean && apt-get update

COPY processor/requirements.txt /processor/requirements.txt
COPY tests/requirements.txt /test/requirements.txt

RUN pip install -r /processor/requirements.txt
RUN pip install -r /test/requirements.txt

# source code mounted via volume by docker-compose.test.yml
#   for quicker development iteration
# COPY processor/ /processor
# COPY test/ /test

CMD ["pytest", "-s", "/tests" ]
